### ISSUE TITLE
关于使用https的解决方案

### ISSUE THREAD

**Issue by Kom3ng** [djdjz7/evaluation-anywhere#1]
由于中育的api不支持https协议，搭建了一个反向代理来解决使用https的问题(以及可能以后会加的CORS)。
使用方式: 将 http://sxz.api6.zykj.org 替换为 https://proxy.astrack.me/zykj (例如: https://proxy.astrack.me/zykj/api/TokenAuth/Login)
但是会带来性能上的损失。(大约600ms)

**Comment by illusionaries** [comment]
谢谢！
已经可以在登录界面和主页面切换了！
![image](https://github.com/djdjz7/evaluation-anywhere/assets/48580179/fc7ba4b7-6111-4940-9796-75c9f2ddfd22)
